"""Reset Tab1 balance, positions, and history (legacy shortcut).

Usage (from repo root):
    .\\.venv\\Scripts\\python.exe scripts/reset_tab1.py
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from scripts._paths import STATE_FILE

if os.path.exists(STATE_FILE):
    with open(STATE_FILE, "r") as f:
        state = json.load(f)
    
    # 1. Reset Balance and Unrealized PnL for Tab 1
    if "balances" in state and "Tab1" in state["balances"]:
        state["balances"]["Tab1"] = 10000.0
    if "unrealized_pnls" in state and "Tab1" in state["unrealized_pnls"]:
        state["unrealized_pnls"]["Tab1"] = 0.0
        
    # 2. Clear all Open Positions generated by Tab 1
    if "open_positions" in state:
        keys_to_delete = [k for k, v in state["open_positions"].items() if v.get("tab") == "Tab1"]
        for k in keys_to_delete:
            del state["open_positions"][k]
            
    # 3. Clear History of Tab 1
    if "history" in state:
        state["history"] = [h for h in state["history"] if h.get("tab") != "Tab1"]
        
    # Write back the reset data to file
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=4)
        
    print("Tab 1 has been successfully reset! ($10,000 Starting Balance & History Cleared)")
else:
    print("No paper_state.json found. Nothing to reset.")
